### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by HanHan666666** [HanHan666666/nodejsPrinter#1]
文件上传完成之后会有如下报错，但是文件上传成功，服务器继续运行。
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (d:\loook\nodejsPrinter\node_modules\express\lib\response.js:776:10)
    at ServerResponse.send (d:\loook\nodejsPrinter\node_modules\express\lib\response.js:170:12)
    at done (d:\loook\nodejsPrinter\node_modules\express\lib\response.js:1013:10)
    at Object.exports.renderFile (d:\loook\nodejsPrinter\node_modules\jade\lib\index.js:374:12)
    at View.exports.__express [as engine] (d:\loook\nodejsPrinter\node_modules\jade\lib\index.js:417:11)
    at View.render (d:\loook\nodejsPrinter\node_modules\express\lib\view.js:135:8)
    at tryRender (d:\loook\nodejsPrinter\node_modules\express\lib\application.js:640:10)
    at Function.render (d:\loook\nodejsPrinter\node_modules\express\lib\application.js:592:3)
```

**Comment by HanHan666666** [comment]
注释掉upload.js中的res.send('上传成功\n');
![image](https://user-images.githubusercontent.com/60591430/160954954-f6084b6d-4c26-4974-9159-62fa27c8aca5.png)
![image](https://user-images.githubusercontent.com/60591430/160954985-00dddb73-be7b-4e7e-a112-531919a7f9d5.png)
